"""Parse trusted log fields; never look for an arbitrary IP in a log message."""

import json
import re
from urllib.parse import urlsplit
from .common import address


def remote(value):
    value = str(value)
    if value.startswith(("ipv4:", "ipv6:")):
        value = value[5:]
    try:
        return address(value)
    except ValueError:
        if value.startswith("[") and "]:" in value:
            return address(value[1:value.index("]")])
        if value.count(":") == 1:
            host, port = value.rsplit(":", 1)
            if port.isdecimal():
                return address(host)
    raise ValueError("Log record does not contain an unambiguous client address")


def ssh(message):
    match = re.search(r"(?:^|sshd(?:\[\d+\])?: )Failed (?:password|publickey|keyboard-interactive/pam) for (?:invalid user )?[^\r\n]+ from (\S+) port \d+(?: ssh\d)?(?: \[preauth\])?$", message)
    return remote(match[1]) if match else None


def gitea(message):
    if "publicKeyHandler()" in message:
        return None  # Gitea can log rejected key probes before successful SSH auth.
    # Split at the FIRST severity marker, so an injected marker in a username
    # cannot make a different substring look like a genuine application record.
    body = re.split(r"\[(?:W|I|E)\] ", message, maxsplit=1)[-1]
    body = re.sub(r"^\[[a-fA-F0-9]+\] ", "", body)
    match = re.fullmatch(r"(?:Failed authentication attempt for \S+|invalid credentials) from (\S+?)(?:: [^\r\n]*)?", body)
    return remote(match[1]) if match else ssh(message)


def organizr(message):
    record = json.loads(message)
    if record.get("channel") == "Authentication" and record.get("message") in ("Wrong Password", "Incorrect 2FA"):
        return remote(record["remote_ip_address"])
    return None


def samba(message):
    # Samba may put indentation before the JSON object.
    if not message.lstrip().startswith("{"):
        return None
    record = json.loads(message)
    if record.get("type") != "Authentication":
        return None
    auth = record.get("Authentication", {})
    if auth.get("status") in ("NT_STATUS_LOGON_FAILURE", "NT_STATUS_WRONG_PASSWORD",
                              "NT_STATUS_NO_SUCH_USER", "NT_STATUS_ACCOUNT_LOCKED_OUT"):
        return remote(auth["remoteAddress"])
    return None


CLF = re.compile(r'^(\S+) - \S+ \[[^\]]+\] "(\w+) ([^" ]+) HTTP/[^" ]+" (\d{3}) \S+ "(?:[^"\\]|\\.)*" "(?:[^"\\]|\\.)*" \d+ "([^" ]+)" "([^" ]+)" \S+$')


def ns8(message):
    if message.startswith("{"):
        record = json.loads(message)
        method, path = record.get("RequestMethod"), record.get("RequestPath", "")
        status, router = record.get("DownstreamStatus"), record.get("RouterName", "")
        backend = record.get("ServiceURL", "")
        ip = record.get("ClientHost") or record.get("ClientAddr", "")
    else:
        match = CLF.fullmatch(message)
        if not match:
            return None
        ip, method, path, status, router, backend = match.groups()
    # The router and backend are generated by Traefik, not user-supplied headers.
    if (method == "POST" and urlsplit(path).path == "/cluster-admin/api/login"
            and str(status) == "401" and router == "cluster-admin-https@file"
            and backend.rstrip("/") == "http://127.0.0.1:9311"):
        return remote(ip)
    return None


PARSERS = {"sshd": ssh, "gitea": gitea, "organizr": organizr, "samba": samba, "ns8": ns8}


def parse(jail, message):
    try:
        # Container stdout records commonly retain their final newline in the
        # systemd journal. Keep strict, whole-record parsers while normalizing
        # only that transport delimiter.
        return PARSERS[jail](message.rstrip("\r\n"))
    except (ValueError, KeyError, TypeError, AttributeError):
        return None
